# Simple workflow for deploying Web SDK Sample to GitHub Pages
name: Deploy Web SDK Sample to Github Pages

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'web/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow comment on PRs
permissions:
  contents: read
  pull-requests: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  web-sdk-sample-deploy:
    runs-on: ubuntu-latest
    env:
      SAMPLE_DIR: web/samples/WordWiz
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Enable pnpm
        run: |
          corepack enable
          corepack use pnpm@10.8.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ env.SAMPLE_DIR }}

      - name: Build
        run: pnpm run build
        working-directory: ${{ env.SAMPLE_DIR }}

      - name: Publish Web SDK Sample Build
        run: ./build/bin/upload-web-sdk-sample-build.sh
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_WEB_SDK_SAMPLE_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GIT_WEB_SDK_SAMPLE_PASSWORD }}
          SAMPLE_DIR: ${{ env.SAMPLE_DIR }}
          
      - uses: github-actions-up-and-running/pr-comment@v1.0.1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Web SDK Sample Build [link](https://beamable.github.io/web-sdk-sample/)
